name = "ProjecturedRST"
uuid = "831b768c-bfea-4983-ba67-a56f379c3222"
version = "0.1.1"
authors = []

[deps]
ProjecturedKernel = "a3e3499a-684d-4df9-a0d6-de2d1797b1f3"
ProjecturedPlatform = "b21cb890-5227-4e91-ae0e-8ab4d844f9f7"

[compat]
ProjecturedKernel = "0.1.1"
ProjecturedPlatform = "0.2.0"
julia = "1.12"

[auto-integration]
default = "auto"

    [auto-integration.triggers]
    Projectured = "92922de3-b970-4d9a-8b2a-9d6f361397b5"
