name = "ProjecturedDataFrames"
uuid = "56a0c30a-96eb-4614-b42e-73838bfa8222"
version = "0.1.0"
authors = []

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ProjecturedKernel = "a3e3499a-684d-4df9-a0d6-de2d1797b1f3"
ProjecturedPlatform = "b21cb890-5227-4e91-ae0e-8ab4d844f9f7"

[compat]
DataFrames = "1"
ProjecturedKernel = "0.1.0"
ProjecturedPlatform = "0.1.0"
julia = "1.12"

[auto-integration]
default = "auto"

    [auto-integration.triggers]
    DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
    Projectured = "92922de3-b970-4d9a-8b2a-9d6f361397b5"
