name = "ProjecturedDataFramesExample"
uuid = "61ad9eff-ea91-43c8-867c-8ad08b1239de"
version = "0.1.1"
authors = []

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ProjecturedDataFrames = "56a0c30a-96eb-4614-b42e-73838bfa8222"

[compat]
DataFrames = "1"
ProjecturedDataFrames = "0.1.1"
julia = "1.12"
